import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/clothing_item.dart';
// Import your MLService
import '../services/ml_service.dart';

class UploadController extends ChangeNotifier {
  final SupabaseClient _supabase = Supabase.instance.client;
  final MLService _mlService = MLService(); // Instance of ML Service

  File? _selectedImage;
  bool _isLoading = false;

  // Controllers for text fields (to allow manual editing)
  final TextEditingController subCategoryController = TextEditingController();
  final TextEditingController articleTypeController = TextEditingController();
  final TextEditingController baseColourController = TextEditingController();
  final TextEditingController usageController = TextEditingController();
  final TextEditingController genderController = TextEditingController();
  
  // Store the extracted embedding
  List<double> _currentEmbedding = [];

  File? get selectedImage => _selectedImage;
  bool get isLoading => _isLoading;

  UploadController() {
    // Load ML model when controller initializes
    _initModel();
  }

  Future<void> _initModel() async {
    await _mlService.loadModel();
  }

  Future<void> pickImage(ImageSource source) async {
    final returnedImage = await ImagePicker().pickImage(source: source);
    if (returnedImage == null) return;

    _selectedImage = File(returnedImage.path);
    notifyListeners();
    
    // Auto-classify immediately after picking
    await _classifyImage();
  }

  Future<void> _classifyImage() async {
    if (_selectedImage == null) return;

    try {
      _setLoading(true);
      
      // Run inference
      final result = _mlService.classifyAndExtract(_selectedImage!);
      
      // Parse results
      final tags = result['tags'] as Map<String, String>;
      _currentEmbedding = result['embedding'] as List<double>;

      // Auto-fill text controllers with predictions
      // Ensure keys match exactly what's in label_maps.json
      subCategoryController.text = tags['subCategory'] ?? '';
      articleTypeController.text = tags['articleType'] ?? '';
      baseColourController.text = tags['baseColour'] ?? '';
      usageController.text = tags['usage'] ?? '';
      genderController.text = tags['gender'] ?? '';

    } catch (e) {
      print('Classification error: $e');
      // Show error snackbar or handle appropriately
    } finally {
      _setLoading(false);
    }
  }

  Future<void> uploadItem(BuildContext context) async {
    if (_selectedImage == null) return;
    
    try {
      _setLoading(true);
      final userId = _supabase.auth.currentUser!.id;
      final fileName = '${DateTime.now().millisecondsSinceEpoch}.jpg';
      
      // 1. Upload Image to Supabase Storage
      await _supabase.storage.from('clothing_items').upload(
        '$userId/$fileName',
        _selectedImage!,
      );
      
      final imageUrl = _supabase.storage.from('clothing_items').getPublicUrl('$userId/$fileName');

      // 2. Save Metadata + Embedding to Database
      final newItem = ClothingItem(
        id: '', // Generated by DB
        userId: userId,
        imageUrl: imageUrl,
        subCategory: subCategoryController.text, // User-corrected values
        articleType: articleTypeController.text,
        baseColour: baseColourController.text,
        usage: usageController.text,
        gender: genderController.text,
        createdAt: DateTime.now(),
        embedding: _currentEmbedding, // Save the vector!
      );

      // Exclude 'id' and 'created_at' for insert if they are auto-generated
      var itemData = newItem.toJson();
      itemData.remove('id'); 
      itemData.remove('created_at');

      await _supabase.from('clothing_items').insert(itemData);

      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Item uploaded successfully!')),
        );
        clearSelection();
        Navigator.pop(context); // Go back or to closet
      }
    } catch (e) {
      print('Upload error: $e');
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error uploading item: $e')),
        );
      }
    } finally {
      _setLoading(false);
    }
  }

  void clearSelection() {
    _selectedImage = null;
    subCategoryController.clear();
    articleTypeController.clear();
    baseColourController.clear();
    usageController.clear();
    genderController.clear();
    _currentEmbedding = [];
    notifyListeners();
  }

  void _setLoading(bool value) {
    _isLoading = value;
    notifyListeners();
  }
}
